### ISSUE TITLE
Not able to login as a admin

### ISSUE THREAD

**Issue by Vaibhav-Singh2110** [sabbir-hossain-abir/Bike-Rental-System#6]
In frontend there is no way to register admin

**Comment by sabbir-hossain-abir** [comment]
You have to add your MongoDB database cluster link in the config.env file. If you want to run the front end you have to execute the command "npm start" for the back end you have to execute the command "nodemon server". After that, you have to create an admin folder just like the user folder in the MongoDB database. If you already have one named admin you have to copy a user with a known username and password from the user list and paste it to the admin folder, then delete the user information from the user and just keep it in the admin folder.

**Comment by Vaibhav-Singh2110** [comment]
Thanks for the reply.
It started working.
Thank you so much
